---
- hosts: spectorious
  vars_files:
    - vars.yml
  tasks:

    - name: Clone/Update Spectorious repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        accept_hostkey: yes
        update: yes
        key_file: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

    - name: Execute setup.sh script
      shell: ./setup.sh "{{ clickhouse_server }}" "{{ clickhouse_password }}" "{{ mongodb_server }}" "{{ mongodb_password }}" "{{ mpop_mongodb_server }}" "{{ mpop_mongodb_password }}"
      args:
        chdir: "{{ ansible_env.HOME }}/work/specorius"
      register: script_output

    - name: Display script output
      debug:
        msg: "{{ script_output.stdout_lines }}"