---
- hosts: spectorious
  vars_files:
    - vars.yml

  tasks:

    - name: Check if repository directory exists
      ansible.builtin.stat:
        path: "{{ repo_dest }}/.git"
      register: repo_check

    - name: Stash local changes if repo exists
      ansible.builtin.shell: git stash
      args:
        chdir: "{{ repo_dest }}"
      when: repo_check.stat.exists

    - name: Clone/Update Spectorious repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ branch }}"
        accept_hostkey: yes
        update: yes
        key_file: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

    - name: Execute setup.sh script
      ansible.builtin.shell: >
        ./setup.sh
        "{{ clickhouse_server }}"
        "{{ clickhouse_password }}"
        "{{ mongodb_server }}"
        "{{ mongodb_password }}"
        "{{ mpop_mongodb_server }}"
        "{{ mpop_mongodb_password }}"
      args:
        chdir: "{{ repo_dest }}"
      register: script_output

    - name: Display script output
      ansible.builtin.debug:
        msg: "{{ script_output.stdout_lines }}"
