---
# tasks/clone_repo.yml
# Clone or update the Spectorious git repository.

- name: Check if Spectorious repo already exists
  ansible.builtin.stat:
    path: "{{ repo_dest }}/.git"
  register: spectorious_dir
  when: not is_local | bool

- name: Stash any local changes before updating (if repo exists)
  ansible.builtin.command: git stash
  args:
    chdir: "{{ repo_dest }}"
  changed_when: false
  failed_when: false
  when: not is_local | bool and spectorious_dir.stat.exists

- name: Clone or update Spectorious repository
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ branch | default(Spectorious_branch) }}"
    accept_hostkey: true
    update: true
    key_file: "{{ private_key_file }}"
  when: not is_local | bool
